FROM influx6/gcloud-golang-1.11.2-pubsub-emulator-base:0.1

ENV GO111MODULE=on

RUN apk --no-cache add git

COPY . $GOPATH/github.com/gokit/actorkit
WORKDIR $GOPATH/github.com/gokit/actorkit

CMD "sh ./scripts/pubsub-tests.sh"

