FROM anapsix/alpine-java
MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

ENV  GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc \
        GLIBC_VERSION=2.28-r0 \
         LANG=C.UTF-8

RUN mkdir /scripts
ADD *.sh /scripts/

RUN set -ex && sh /scripts/kafkasetup.sh


