FROM influx6/redis-golang-1.11.2-base:0.1

ENV GO111MODULE=on

RUN apk --no-cache add git

COPY . $GOPATH/github.com/gokit/actorkit
WORKDIR $GOPATH/github.com/gokit/actorkit

CMD "sh ./scripts/redis-tests.sh"

