FROM influx6/nats-golang-1.11.2-debian-base:0.1

ENV GO111MODULE=on

RUN apk --no-cache add git

COPY . $GOPATH/github.com/gokit/actorkit
WORKDIR $GOPATH/github.com/gokit/actorkit

CMD "sh ./scripts/nats-tests.sh"

